KycService:
  Db:
    LogsConnString:
      settings-key: KycService-LogsConnString
      types:
        - AzureTableStorage
    DbConnString:
      settings-key: KycService-DbConnString
  Rabbit:
    Publishers:
      ConnectionString:
        settings-key: UserManagementRabbitMQ
        types:
          - RabbitMq
    Subscribers:
      ConnectionString:
        settings-key: UserManagementRabbitMQ
        types:
          - RabbitMq
  BackOfficeLink:
    settings-key: AdminManagementService-BackOfficeLink
  KycApprovedEmail:
    EmailTemplateId:
      settings-key: KycService-KycApprovedEmail-EmailTemplateId
    SubjectTemplateId:
      settings-key: KycService-KycApprovedEmail-SubjectTemplateId
    VoucherManagerUrl:
      settings-key: KycService-KycApprovedEmail-VoucherManagerUrl
  KycRejectedEmail:
    EmailTemplateId:
      settings-key: KycService-KycRejectedEmail-EmailTemplateId
    SubjectTemplateId:
      settings-key: KycService-KycRejectedEmail-SubjectTemplateId
SlackNotifications:
    AzureQueue:
        ConnectionString:
            settings-key: SlackNotificationsConnString
            types:
                - AzureTableStorage
        QueueName:
            settings-key: SlackQueueName
MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: MonitoringServiceUrl
PartnerManagementService:
  ServiceUrl:
    settings-key: PartnerManagementServiceUrl
AdminManagementService:
  ServiceUrl:
    settings-key: AdminManagementServiceUrl